name: 5 mintues closeLottery cron job
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: 5 mintues closeLottery cron job
        run: |
          curl --request POST \
          --url 'https://sino-realrufans.vercel.app/api/closelottery' \
          --header 'Authorization: ${{ secrets.ACTION_KEY }}'